name: CRD sync check latest fr branch

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch:

jobs:
  call-build-workflow:
    if: github.repository_owner == 'openstack-k8s-operators'
    uses: ./.github/workflows/crd-sync-check.yaml
    with:
      branch_name: 18.0-fr5
